// src/components/Toolbar.vue
<script setup lang="ts">
import { 
  Upload, 
  Save, 
  CloudUpload, 
  CloudDownload, 
  FileText 
} from 'lucide-vue-next';
import Button from '@/components/ui/Button.vue';

defineProps<{
  isLoading: boolean;
}>();

const emit = defineEmits<{
  (e: 'load-file', event: Event): void;
  (e: 'save-file'): void;
  (e: 'save-api'): void;
  (e: 'load-api'): void;
}>();

// Wrapper to cast Event target to HTMLInputElement for the parent
const onFileChange = (e: Event) => emit('load-file', e);
</script>

<template>
  <header class="flex items-center justify-between h-14 px-4 border-b bg-background">
    <div class="flex items-center">
      <FileText class="w-6 h-6 mr-2" />
      <h1 class="text-xl font-bold tracking-tight">Markdown Previewer</h1>
    </div>

    <div class="flex items-center gap-2">
      
      <label for="file-upload" class="cursor-pointer" title="Upload from device (.md)">
        <Button variant="ghost" size="icon" :disabled="isLoading" class="pointer-events-none">
          <Upload class="h-4 w-4" />
        </Button>
        <input
          id="file-upload"
          type="file"
          accept=".md,.txt"
          class="hidden"
          @change="onFileChange"
          :disabled="isLoading"
        />
      </label>

      <Button 
        variant="ghost" 
        size="icon" 
        @click="emit('save-file')" 
        :disabled="isLoading"
        title="Save to Computer (.md)"
      >
        <Save class="h-4 w-4" />
      </Button>

      <div class="h-6 w-px bg-border mx-2"></div>

      <Button 
        variant="ghost" 
        size="icon" 
        @click="emit('save-api')" 
        :disabled="isLoading"
        title="Save to Cloud"
      >
        <CloudUpload class="h-4 w-4" />
      </Button>

      <Button 
        variant="ghost" 
        size="icon" 
        @click="emit('load-api')" 
        :disabled="isLoading"
        title="Load from Cloud"
      >
        <CloudDownload class="h-4 w-4" />
      </Button>

      <span v-if="isLoading" class="text-sm animate-pulse ml-2">Processing...</span>
    </div>
  </header>
</template>

// src/components/Toolbar.tsx
import { FaFileUpload, FaSave, FaCloudUploadAlt, FaCloudDownloadAlt } from 'react-icons/fa';
import { Button } from '@/components/ui/button';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { Separator } from '@/components/ui/separator';

interface ToolbarProps {
  onLoadFile: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onSaveFile: () => void;
  onSaveToApi: () => void;
  onLoadFromApi: () => void;
  isLoading: boolean;
}

export function Toolbar({ onLoadFile, onSaveFile, onSaveToApi, onLoadFromApi, isLoading }: ToolbarProps) {
  return (

    <TooltipProvider delayDuration={100}>
      <header className="flex items-center justify-between h-14 px-4 border-b bg-background">
        {/* Left Side: Title */}
        <div className="flex items-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="1"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="w-6 h-6 mr-2"
          >
            <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
            <polyline points="14 2 14 8 20 8" />
            <line x1="16" y1="13" x2="8" y2="13" />
            <line x1="16" y1="17" x2="8" y2="17" />
            <line x1="10" y1="9" x2="8" y2="9" />
          </svg>
          <h1 className="text-xl font-bold tracking-tight">Markdown Previewer</h1>
        </div>

        {/* Right Side: Action Buttons */}
        <div className="flex items-center gap-2">
          {/* Local File Actions */}
          <Tooltip>
            <TooltipTrigger asChild>
              <label htmlFor="file-upload">
                <Button variant="ghost" size="icon" disabled={isLoading} className="cursor-pointer">
                  <FaFileUpload className="h-4 w-4" />
                </Button>
                <input
                  id="file-upload"
                  type="file"
                  accept=".md,.txt"
                  className="hidden"
                  onChange={onLoadFile}
                  disabled={isLoading}
                />
              </label>
            </TooltipTrigger>
            <TooltipContent>
              <p>Upload from device (.md)</p>
            </TooltipContent>
          </Tooltip>

          <Tooltip>
            <TooltipTrigger asChild>
              <Button variant="ghost" size="icon" onClick={onSaveFile} disabled={isLoading}>
                <FaSave className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>
              <p>Save to Computer (.md)</p>
            </TooltipContent>
          </Tooltip>

          <Separator orientation="vertical" className="h-6 mx-2" />

          {/* Cloud Actions */}
          <Tooltip>
            <TooltipTrigger asChild>
              <Button variant="ghost" size="icon" onClick={onSaveToApi} disabled={isLoading}>
                <FaCloudUploadAlt className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>
              <p>Save to Cloud</p>
            </TooltipContent>
          </Tooltip>

          <Tooltip>
            <TooltipTrigger asChild>
              <Button variant="ghost" size="icon" onClick={onLoadFromApi} disabled={isLoading}>
                <FaCloudDownloadAlt className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>
              <p>Load from Cloud</p>
            </TooltipContent>
          </Tooltip>
          {isLoading && <span className="text-sm animate-pulse">Processing...</span>}
        </div>
      </header>
    </TooltipProvider>
  );
}
